import { themeQuartz } from 'ag-grid-community';

/** Persian locale for AG Grid Community UI strings. */
export const faLocaleText: Record<string, string> = {
  // pagination
  page: 'صفحه',
  more: 'بیشتر',
  to: 'تا',
  of: 'از',
  nextPage: 'صفحه بعد',
  lastPage: 'صفحه آخر',
  firstPage: 'صفحه اول',
  previousPage: 'صفحه قبل',
  pageSizeSelectorLabel: 'تعداد ردیف در صفحه:',
  // filters
  filterOoo: 'فیلتر...',
  equals: 'مساوی',
  notEqual: 'نامساوی',
  blank: 'خالی',
  notBlank: 'نامخلص',
  empty: 'انتخاب کنید',
  lessThan: 'کمتر از',
  greaterThan: 'بیشتر از',
  lessThanOrEqual: 'کمتر یا مساوی',
  greaterThanOrEqual: 'بیشتر یا مساوی',
  inRange: 'در بازه',
  inRangeStart: 'از',
  inRangeEnd: 'تا',
  contains: 'شامل',
  notContains: 'شامل نیست',
  startsWith: 'شروع با',
  endsWith: 'پایان با',
  andCondition: 'و',
  orCondition: 'یا',
  applyFilter: 'اعمال',
  resetFilter: 'بازنشانی',
  clearFilter: 'پاک‌سازی',
  cancelFilter: 'انصراف',
  searchOoo: 'جستجو...',
  selectAll: 'همه',
  // columns
  pinColumn: 'سنجاق ستون',
  pinLeft: 'سنجاق به چپ',
  pinRight: 'سنجاق به راست',
  noPin: 'برداشتن سنجاق',
  autosizeThisColumn: 'اندازه خودکار این ستون',
  autosizeAllColumns: 'اندازه خودکار همه ستون‌ها',
  resetColumns: 'بازنشانی ستون‌ها',
  columnFilter: 'فیلتر ستون',
  columnChooser: 'انتخاب ستون‌ها',
  sortAscending: 'مرتب‌سازی صعودی',
  sortDescending: 'مرتب‌سازی نزولی',
  sortUnSort: 'حذف مرتب‌سازی',
  // misc
  noRowsToShow: 'ردیفی برای نمایش وجود ندارد',
  loadingOoo: 'در حال بارگذاری...',
  loadingError: 'خطا در بارگذاری',
  true: 'بله',
  false: 'خیر',
  invalidDate: 'تاریخ نامعتبر',
  invalidNumber: 'عدد نامعتبر',
  selectAllSearchResults: 'انتخاب همه نتایج جستجو',
  searchFilterValues: 'جستجوی مقادیر...',
};

/** Compact Excel-like quartz theme. */
export const gridTheme = themeQuartz.withParams({
  accentColor: '#1D4ED8',
  backgroundColor: '#ffffff',
  foregroundColor: '#1e293b',
  borderColor: '#E2E8F0',
  fontFamily: 'inherit',
  fontSize: 12.5,
  headerFontSize: 12,
  headerFontWeight: 700,
  headerHeight: 44,
  headerBackgroundColor: '#F1F5F9',
  oddRowBackgroundColor: '#F8FAFC',
  rowHoverColor: '#EFF5FF',
  selectedRowBackgroundColor: '#DBEAFE',
  rowHeight: 34,
  spacing: 6,
  wrapperBorderRadius: 12,
  cellHorizontalPadding: 10,
  columnBorder: true,
});
